### ISSUE TITLE
Excluding pack from project dependencies

### ISSUE THREAD

**Issue by viesti** [juxt/pack.alpha#54]
A [discussion on Clojurians Slack](https://clojurians.slack.com/archives/C03S1KBA2/p1564059306190100) yesterday got me thinking on how the dependencies that pack uses mix with the dependencies of a project. Even if pack is behind an alias, a `clojure -A:pack` invocation in a project directory will pick up deps under `:deps` key, which might cause confusion at least (in the Slack discussion case, Jib debug logging was turned on). This can be avoided by having project dependencies behind an alias, and passing that alias to pack arguments, but not to `clojure` invocation, e.g.

```
clojure \
  -A:pack \ # <-- pick up pack
  -m mach.pack.alpha.jib \ # use pack command
  ...command args... \
  -A main  # <-- tell pack which project aliases to include
```

Also, it seems that [clj.native-image](https://github.com/taylorwood/clj.native-image/blob/master/src/clj/native_image.clj#L14]) does some work on excluding itself from the target classpath. I wonder if pack could do something like that.

**Comment by SevereOverfl0w** [comment]
I would not recommend keeping your dependencies in an alias, like main, because then your project cannot be consumed via git or local/root.

clj.native-image works like that because it operates from the REPL, not on the deps.edn file directly. The approach isn't applicable to pack. That's why it must exclude itself.

Pack used to have a `-d deps.edn` flag intended for this case, but it wasn't well supported by t.d.a, especially for local dependencies.  That's probably changed now with the latest tdeps releases where you can bind the location to a dynamic var.

**Comment by viesti** [comment]
Right. If pack is used via an alias, it won't get included into the project dependencies. Pack dependencies merge with project dependencies only on the pack command invocation and in this specific case, adding suitable logging libraries to a project, end up turning Jib debug logging on, which is quite verbose and [trying to silence logging via `TIMBRE_LEVEL` system property ends up causing an exception](https://github.com/ptaoussanis/timbre/issues/294). 

My logging setup skills are lacking to find an answer for the original problem though, I'll look into it when I have time :)

**Comment by SevereOverfl0w** [comment]
There's a new feature where you can have :deps in an alias to override the project dependencies.

This should fix the issue.

**Comment by SevereOverfl0w** [comment]
#65 is the tracking issue for the enhancement that will fix this.

**Comment by viesti** [comment]
Best kind of fix, sorts it self out by waiting :D
